//
//  misc.h
//  TextureExtractorV2
//
//  Created by Danil Luzin on 08/03/2018.
//  Copyright © 2018 Danil Luzin. All rights reserved.
//

#ifndef misc_h
#define misc_h

#include<iostream>

static const std::string exampleIni ="\n"
"[basics]\n"
"\n"
"objFilePath = resources/slany/slany_cut4_uvseperate.obj\n"
"\n"
"cameraListFilePath = resources/slany/list3.txt\n"
"\n"
"cameraInfoPath = resources/slany/bundle.rd.out\n"
"\n"
"photoFolderPath = resources/slany\n"
"\n"
"newTextureFolderPath = working_resources/slany/derived9\n"
"\n"
"textureWidth = 4000\n"
"textureHeight = 4000\n"
"\n"
"getLabelingFromFile = false\n"
"\n"
"writeLabelingToFile = true\n"
"\n"
"getDataCostsFromFile = true\n"
"\n"
"writeDataCostsToFile = true\n"
"\n"
"verbose = true\n"
"\n"
"imageFormat = png\n"
"\n"
"threadCount = 4\n"
"\n"
"\n"
"\n"
"[optional]\n"
"\n"
"labelingFilePath = working_resources/slany/derived9/new_labeling.txt\n"
"\n"
"newLabelingFilePath = working_resources/slany/derived9/new_labeling.txt\n"
"\n"
"dataCostsFilePath = working_resources/slany/derived9/out_dataCosts.txt\n"
"\n"
"newDataCostsFilePath = working_resources/slany/derived9/out_dataCosts.txt\n"
"\n"
"addProjectNameToFiles = true\n"
"\n"
"projectName = slanyOut\n"
"\n"
"doGloabalAdjustment = true\n"
"\n"
"doSeamLeveling = true\n"
"\n"
"doTextureExtension = true\n"
"\n"
"doColorConsistency = true\n"
"\n"
"colorConsistencyThreshold = 0.7\n"
"\n"
"[perfomance]\n"
"\n"
"BVHMinNode = 200;\n"
"\n"
"\n"
"\n"
"[debug]\n"
"\n"
"genRawTexture = false\n"
"\n"
"genLevelingTexture = false\n"
"\n"
"genMaskTexture = false\n"
"\n"
"genLebelingTexture = false\n"
"\n"
"genGlobalTexture = false\n"
"\n"
"justRender = false\n"
"\n"
"renderInTheEnd = false\n"
"\n"
"rasterLabelAssignmentFolder = working_resources/slany/derived9/labeling\n"
"\n"
"resultRenderFolder = working_resources/slany/derived9/res\n"
"\n"
"rasterLabelAssignment = true\n"
"\n"
"";

#endif /* misc_h */
